---
# playbook.yml
- name: "Install Vault"
  hosts: default
  become: true
  vars:
    vault_version: 1.4.0

  tasks:
  - name: Install unzip
    apt:
      update_cache: yes
      name: unzip
      state: latest

  - name: Create Vault Group
    group:
      name: vault
      state: present

  - name: Create Vault User
    user:
      name: vault
      state: present
      groups:
        - vault

  - name: Create Ubuntu User
    user:
      name: ubuntu
      state: present

  - name: Add Vault user to sudoers
    lineinfile:
      path: /etc/sudoers
      line: "vault ALL=(ALL) NOPASSWD: ALL"
      state: present

  - name: Define trusted keys path
    lineinfile:
      path: /etc/ssh/sshd_config
      insertafter: ^#AuthorizedKeysFile
      line: "TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem"
      state: present


  - name: Download Vault Binary
    get_url:
      url: https://releases.hashicorp.com/vault/{{ vault_version }}+ent/vault_{{ vault_version }}+ent_linux_amd64.zip
      dest: ./vault.zip
      checksum: sha256:https://releases.hashicorp.com/vault/{{ vault_version }}+ent/vault_{{ vault_version }}+ent_SHA256SUMS

  - name: Unpack Vault Binary
    unarchive:
      remote_src: yes
      src: ./vault.zip
      dest: /usr/local/bin/

  - name: Set Vault Binary Owner
    file:
      path: /usr/local/bin/vault
      owner: vault
      group: vault
      mode: +x

  - name: Copy Vault systemd
    copy:
      src: ./vault.service
      dest: /etc/systemd/system/vault.service
      owner: root
      group: root
      mode: '0644'

  - name: Create Vault conf directory
    file:
      path: /etc/vault.d
      state: directory
      owner: vault
      group: vault

  - name: Create Vault pid directory
    file:
      path: /run/vault
      state: directory
      owner: vault
      group: vault

  - name: Disable Vault Service
    systemd:
      name: vault
      enabled: no

  - name: Install nginx
    apt:
      name: nginx
      state: latest